// Generated by `dart run ffigen` from libsimbox's simbox_api.h/
// simbox_types.h (libsCpp/asterisk_chan_simbox). Do not hand-edit —
// see ../../../ffigen.yaml and flows/sdd-flutter_gsm-ffi.
// ignore_for_file: always_specify_types, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Dart FFI bindings for libsimbox's public C API (simbox_api.h), generated from the native SDK shipped by sdd-asterisk-chan-simbox.
///
class SimboxBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SimboxBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SimboxBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ========================================================================= */
  /// /* 5. Raw AT Commands & Diagnostics                                          */
  /// /* =========================================================================
  int simbox_at_command(
    simbox_device_t dev,
    ffi.Pointer<ffi.Char> cmd,
    ffi.Pointer<ffi.Char> response_buf,
    int buf_len,
  ) {
    return _simbox_at_command(dev, cmd, response_buf, buf_len);
  }

  late final _simbox_at_commandPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            simbox_device_t,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('simbox_at_command');
  late final _simbox_at_command = _simbox_at_commandPtr
      .asFunction<
        int Function(
          simbox_device_t,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  int simbox_call_answer(simbox_device_t dev) {
    return _simbox_call_answer(dev);
  }

  late final _simbox_call_answerPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_device_t)>>(
        'simbox_call_answer',
      );
  late final _simbox_call_answer = _simbox_call_answerPtr
      .asFunction<int Function(simbox_device_t)>();

  int simbox_call_hangup(simbox_device_t dev) {
    return _simbox_call_hangup(dev);
  }

  late final _simbox_call_hangupPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_device_t)>>(
        'simbox_call_hangup',
      );
  late final _simbox_call_hangup = _simbox_call_hangupPtr
      .asFunction<int Function(simbox_device_t)>();

  /// ========================================================================= */
  /// /* 3. Voice Calls (SLINEAR 8kHz PCM)                                         */
  /// /* =========================================================================
  int simbox_call_originate(simbox_device_t dev, ffi.Pointer<ffi.Char> number) {
    return _simbox_call_originate(dev, number);
  }

  late final _simbox_call_originatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_device_t, ffi.Pointer<ffi.Char>)
        >
      >('simbox_call_originate');
  late final _simbox_call_originate = _simbox_call_originatePtr
      .asFunction<int Function(simbox_device_t, ffi.Pointer<ffi.Char>)>();

  int simbox_call_read_audio(
    simbox_device_t dev,
    ffi.Pointer<ffi.Int16> pcm_samples,
    int max_count,
  ) {
    return _simbox_call_read_audio(dev, pcm_samples, max_count);
  }

  late final _simbox_call_read_audioPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_device_t, ffi.Pointer<ffi.Int16>, ffi.Size)
        >
      >('simbox_call_read_audio');
  late final _simbox_call_read_audio = _simbox_call_read_audioPtr
      .asFunction<int Function(simbox_device_t, ffi.Pointer<ffi.Int16>, int)>();

  int simbox_call_send_dtmf(simbox_device_t dev, int digit) {
    return _simbox_call_send_dtmf(dev, digit);
  }

  late final _simbox_call_send_dtmfPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_device_t, ffi.Char)>>(
        'simbox_call_send_dtmf',
      );
  late final _simbox_call_send_dtmf = _simbox_call_send_dtmfPtr
      .asFunction<int Function(simbox_device_t, int)>();

  int simbox_call_write_audio(
    simbox_device_t dev,
    ffi.Pointer<ffi.Int16> pcm_samples,
    int count,
  ) {
    return _simbox_call_write_audio(dev, pcm_samples, count);
  }

  late final _simbox_call_write_audioPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_device_t, ffi.Pointer<ffi.Int16>, ffi.Size)
        >
      >('simbox_call_write_audio');
  late final _simbox_call_write_audio = _simbox_call_write_audioPtr
      .asFunction<int Function(simbox_device_t, ffi.Pointer<ffi.Int16>, int)>();

  int simbox_change_imei(simbox_device_t dev, ffi.Pointer<ffi.Char> new_imei) {
    return _simbox_change_imei(dev, new_imei);
  }

  late final _simbox_change_imeiPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_device_t, ffi.Pointer<ffi.Char>)
        >
      >('simbox_change_imei');
  late final _simbox_change_imei = _simbox_change_imeiPtr
      .asFunction<int Function(simbox_device_t, ffi.Pointer<ffi.Char>)>();

  /// ========================================================================= */
  /// /* 2. Modem Device Management (Indexed by Serial Number)                    */
  /// /* =========================================================================
  int simbox_device_count(simbox_handle_t handle) {
    return _simbox_device_count(handle);
  }

  late final _simbox_device_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_handle_t)>>(
        'simbox_device_count',
      );
  late final _simbox_device_count = _simbox_device_countPtr
      .asFunction<int Function(simbox_handle_t)>();

  simbox_device_t simbox_device_get_by_index(
    simbox_handle_t handle,
    int index,
  ) {
    return _simbox_device_get_by_index(handle, index);
  }

  late final _simbox_device_get_by_indexPtr =
      _lookup<
        ffi.NativeFunction<simbox_device_t Function(simbox_handle_t, ffi.Int)>
      >('simbox_device_get_by_index');
  late final _simbox_device_get_by_index = _simbox_device_get_by_indexPtr
      .asFunction<simbox_device_t Function(simbox_handle_t, int)>();

  simbox_device_t simbox_device_get_by_sn(
    simbox_handle_t handle,
    ffi.Pointer<ffi.Char> sn,
  ) {
    return _simbox_device_get_by_sn(handle, sn);
  }

  late final _simbox_device_get_by_snPtr =
      _lookup<
        ffi.NativeFunction<
          simbox_device_t Function(simbox_handle_t, ffi.Pointer<ffi.Char>)
        >
      >('simbox_device_get_by_sn');
  late final _simbox_device_get_by_sn = _simbox_device_get_by_snPtr
      .asFunction<
        simbox_device_t Function(simbox_handle_t, ffi.Pointer<ffi.Char>)
      >();

  int simbox_device_get_info(
    simbox_device_t dev,
    ffi.Pointer<simbox_device_info_t> info,
  ) {
    return _simbox_device_get_info(dev, info);
  }

  late final _simbox_device_get_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_device_t, ffi.Pointer<simbox_device_info_t>)
        >
      >('simbox_device_get_info');
  late final _simbox_device_get_info = _simbox_device_get_infoPtr
      .asFunction<
        int Function(simbox_device_t, ffi.Pointer<simbox_device_info_t>)
      >();

  ffi.Pointer<ffi.Char> simbox_device_imei(simbox_device_t dev) {
    return _simbox_device_imei(dev);
  }

  late final _simbox_device_imeiPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(simbox_device_t)>
      >('simbox_device_imei');
  late final _simbox_device_imei = _simbox_device_imeiPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(simbox_device_t)>();

  ffi.Pointer<ffi.Char> simbox_device_imsi(simbox_device_t dev) {
    return _simbox_device_imsi(dev);
  }

  late final _simbox_device_imsiPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(simbox_device_t)>
      >('simbox_device_imsi');
  late final _simbox_device_imsi = _simbox_device_imsiPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(simbox_device_t)>();

  /// Registers a device found by the discovery subsystem (see section 6)
  /// into this handle's device registry, so it becomes visible to
  /// simbox_device_count()/simbox_device_get_by_index()/get_by_sn() and
  /// operable via the call/SMS/AT-command functions below. Idempotent: a
  /// second registration of an already-known serial number is a no-op that
  /// returns 0 without creating a duplicate entry. Fires
  /// SIMBOX_EVENT_DEVICE_CONNECTED via the registered event callback (see
  /// simbox_set_event_callback) on first registration. Returns 0 on
  /// success, -1 on failure (NULL args or registry full).
  int simbox_device_register(
    simbox_handle_t handle,
    ffi.Pointer<simbox_discovered_device_t> discovered,
  ) {
    return _simbox_device_register(handle, discovered);
  }

  late final _simbox_device_registerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            simbox_handle_t,
            ffi.Pointer<simbox_discovered_device_t>,
          )
        >
      >('simbox_device_register');
  late final _simbox_device_register = _simbox_device_registerPtr
      .asFunction<
        int Function(simbox_handle_t, ffi.Pointer<simbox_discovered_device_t>)
      >();

  int simbox_device_rssi(simbox_device_t dev) {
    return _simbox_device_rssi(dev);
  }

  late final _simbox_device_rssiPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_device_t)>>(
        'simbox_device_rssi',
      );
  late final _simbox_device_rssi = _simbox_device_rssiPtr
      .asFunction<int Function(simbox_device_t)>();

  ffi.Pointer<ffi.Char> simbox_device_sn(simbox_device_t dev) {
    return _simbox_device_sn(dev);
  }

  late final _simbox_device_snPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(simbox_device_t)>
      >('simbox_device_sn');
  late final _simbox_device_sn = _simbox_device_snPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(simbox_device_t)>();

  simbox_device_state_t simbox_device_state(simbox_device_t dev) {
    return simbox_device_state_t.fromValue(_simbox_device_state(dev));
  }

  late final _simbox_device_statePtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(simbox_device_t)>>(
        'simbox_device_state',
      );
  late final _simbox_device_state = _simbox_device_statePtr
      .asFunction<int Function(simbox_device_t)>();

  int simbox_discovery_device_count(simbox_discovery_t handle) {
    return _simbox_discovery_device_count(handle);
  }

  late final _simbox_discovery_device_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_discovery_t)>>(
        'simbox_discovery_device_count',
      );
  late final _simbox_discovery_device_count = _simbox_discovery_device_countPtr
      .asFunction<int Function(simbox_discovery_t)>();

  int simbox_discovery_device_get(
    simbox_discovery_t handle,
    int index,
    ffi.Pointer<simbox_discovered_device_t> device,
  ) {
    return _simbox_discovery_device_get(handle, index, device);
  }

  late final _simbox_discovery_device_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            simbox_discovery_t,
            ffi.Int,
            ffi.Pointer<simbox_discovered_device_t>,
          )
        >
      >('simbox_discovery_device_get');
  late final _simbox_discovery_device_get = _simbox_discovery_device_getPtr
      .asFunction<
        int Function(
          simbox_discovery_t,
          int,
          ffi.Pointer<simbox_discovered_device_t>,
        )
      >();

  int simbox_discovery_scan(simbox_discovery_t handle) {
    return _simbox_discovery_scan(handle);
  }

  late final _simbox_discovery_scanPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_discovery_t)>>(
        'simbox_discovery_scan',
      );
  late final _simbox_discovery_scan = _simbox_discovery_scanPtr
      .asFunction<int Function(simbox_discovery_t)>();

  /// ========================================================================= */
  /// /* 6. Multi-Generation Node Discovery                                        */
  /// /* =========================================================================
  simbox_discovery_t simbox_discovery_start(ffi.Pointer<ffi.Char> config_path) {
    return _simbox_discovery_start(config_path);
  }

  late final _simbox_discovery_startPtr =
      _lookup<
        ffi.NativeFunction<simbox_discovery_t Function(ffi.Pointer<ffi.Char>)>
      >('simbox_discovery_start');
  late final _simbox_discovery_start = _simbox_discovery_startPtr
      .asFunction<simbox_discovery_t Function(ffi.Pointer<ffi.Char>)>();

  void simbox_discovery_stop(simbox_discovery_t handle) {
    return _simbox_discovery_stop(handle);
  }

  late final _simbox_discovery_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(simbox_discovery_t)>>(
        'simbox_discovery_stop',
      );
  late final _simbox_discovery_stop = _simbox_discovery_stopPtr
      .asFunction<void Function(simbox_discovery_t)>();

  /// ========================================================================= */
  /// /* 1. Global Lifecycle & Configuration                                       */
  /// /* =========================================================================
  simbox_handle_t simbox_init(ffi.Pointer<simbox_config_t> config) {
    return _simbox_init(config);
  }

  late final _simbox_initPtr =
      _lookup<
        ffi.NativeFunction<
          simbox_handle_t Function(ffi.Pointer<simbox_config_t>)
        >
      >('simbox_init');
  late final _simbox_init = _simbox_initPtr
      .asFunction<simbox_handle_t Function(ffi.Pointer<simbox_config_t>)>();

  int simbox_prog_change_imei(
    simbox_prog_t handle,
    ffi.Pointer<ffi.Char> new_imei,
  ) {
    return _simbox_prog_change_imei(handle, new_imei);
  }

  late final _simbox_prog_change_imeiPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_prog_t, ffi.Pointer<ffi.Char>)
        >
      >('simbox_prog_change_imei');
  late final _simbox_prog_change_imei = _simbox_prog_change_imeiPtr
      .asFunction<int Function(simbox_prog_t, ffi.Pointer<ffi.Char>)>();

  void simbox_prog_close(simbox_prog_t handle) {
    return _simbox_prog_close(handle);
  }

  late final _simbox_prog_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(simbox_prog_t)>>(
        'simbox_prog_close',
      );
  late final _simbox_prog_close = _simbox_prog_closePtr
      .asFunction<void Function(simbox_prog_t)>();

  int simbox_prog_flash(
    simbox_prog_t handle,
    ffi.Pointer<ffi.Char> usb_device,
    ffi.Pointer<ffi.Char> firmware_path,
    simbox_prog_progress_cb cb,
    ffi.Pointer<ffi.Void> userdata,
  ) {
    return _simbox_prog_flash(handle, usb_device, firmware_path, cb, userdata);
  }

  late final _simbox_prog_flashPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            simbox_prog_t,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            simbox_prog_progress_cb,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('simbox_prog_flash');
  late final _simbox_prog_flash = _simbox_prog_flashPtr
      .asFunction<
        int Function(
          simbox_prog_t,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          simbox_prog_progress_cb,
          ffi.Pointer<ffi.Void>,
        )
      >();

  int simbox_prog_get_progress(simbox_prog_t handle) {
    return _simbox_prog_get_progress(handle);
  }

  late final _simbox_prog_get_progressPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_prog_t)>>(
        'simbox_prog_get_progress',
      );
  late final _simbox_prog_get_progress = _simbox_prog_get_progressPtr
      .asFunction<int Function(simbox_prog_t)>();

  ffi.Pointer<ffi.Char> simbox_prog_get_state(simbox_prog_t handle) {
    return _simbox_prog_get_state(handle);
  }

  late final _simbox_prog_get_statePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(simbox_prog_t)>
      >('simbox_prog_get_state');
  late final _simbox_prog_get_state = _simbox_prog_get_statePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(simbox_prog_t)>();

  /// ========================================================================= */
  /// /* 7. Qualcomm DIAG Programmator & Firmware Flasher                          */
  /// /* =========================================================================
  simbox_prog_t simbox_prog_open(ffi.Pointer<ffi.Char> tty_port) {
    return _simbox_prog_open(tty_port);
  }

  late final _simbox_prog_openPtr =
      _lookup<
        ffi.NativeFunction<simbox_prog_t Function(ffi.Pointer<ffi.Char>)>
      >('simbox_prog_open');
  late final _simbox_prog_open = _simbox_prog_openPtr
      .asFunction<simbox_prog_t Function(ffi.Pointer<ffi.Char>)>();

  int simbox_prog_set_diagmode(simbox_prog_t handle) {
    return _simbox_prog_set_diagmode(handle);
  }

  late final _simbox_prog_set_diagmodePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_prog_t)>>(
        'simbox_prog_set_diagmode',
      );
  late final _simbox_prog_set_diagmode = _simbox_prog_set_diagmodePtr
      .asFunction<int Function(simbox_prog_t)>();

  void simbox_reader_close(simbox_reader_t handle) {
    return _simbox_reader_close(handle);
  }

  late final _simbox_reader_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(simbox_reader_t)>>(
        'simbox_reader_close',
      );
  late final _simbox_reader_close = _simbox_reader_closePtr
      .asFunction<void Function(simbox_reader_t)>();

  int simbox_reader_get_atr(
    simbox_reader_t handle,
    ffi.Pointer<ffi.Char> atr_hex,
    int atr_size,
  ) {
    return _simbox_reader_get_atr(handle, atr_hex, atr_size);
  }

  late final _simbox_reader_get_atrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_reader_t, ffi.Pointer<ffi.Char>, ffi.Size)
        >
      >('simbox_reader_get_atr');
  late final _simbox_reader_get_atr = _simbox_reader_get_atrPtr
      .asFunction<int Function(simbox_reader_t, ffi.Pointer<ffi.Char>, int)>();

  /// ========================================================================= */
  /// /* 8. APDU SIM Reader Interface                                              */
  /// /* =========================================================================
  simbox_reader_t simbox_reader_open(ffi.Pointer<ffi.Char> tty_port) {
    return _simbox_reader_open(tty_port);
  }

  late final _simbox_reader_openPtr =
      _lookup<
        ffi.NativeFunction<simbox_reader_t Function(ffi.Pointer<ffi.Char>)>
      >('simbox_reader_open');
  late final _simbox_reader_open = _simbox_reader_openPtr
      .asFunction<simbox_reader_t Function(ffi.Pointer<ffi.Char>)>();

  int simbox_reader_reset(simbox_reader_t handle) {
    return _simbox_reader_reset(handle);
  }

  late final _simbox_reader_resetPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(simbox_reader_t)>>(
        'simbox_reader_reset',
      );
  late final _simbox_reader_reset = _simbox_reader_resetPtr
      .asFunction<int Function(simbox_reader_t)>();

  int simbox_reader_send_apdu(
    simbox_reader_t handle,
    ffi.Pointer<ffi.Uint8> apdu,
    int len,
    ffi.Pointer<ffi.Uint8> response,
    ffi.Pointer<ffi.Size> resp_len,
  ) {
    return _simbox_reader_send_apdu(handle, apdu, len, response, resp_len);
  }

  late final _simbox_reader_send_apduPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            simbox_reader_t,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('simbox_reader_send_apdu');
  late final _simbox_reader_send_apdu = _simbox_reader_send_apduPtr
      .asFunction<
        int Function(
          simbox_reader_t,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void simbox_set_event_callback(
    simbox_handle_t handle,
    simbox_event_cb cb,
    ffi.Pointer<ffi.Void> userdata,
  ) {
    return _simbox_set_event_callback(handle, cb, userdata);
  }

  late final _simbox_set_event_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            simbox_handle_t,
            simbox_event_cb,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('simbox_set_event_callback');
  late final _simbox_set_event_callback = _simbox_set_event_callbackPtr
      .asFunction<
        void Function(simbox_handle_t, simbox_event_cb, ffi.Pointer<ffi.Void>)
      >();

  void simbox_shutdown(simbox_handle_t handle) {
    return _simbox_shutdown(handle);
  }

  late final _simbox_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(simbox_handle_t)>>(
        'simbox_shutdown',
      );
  late final _simbox_shutdown = _simbox_shutdownPtr
      .asFunction<void Function(simbox_handle_t)>();

  /// ========================================================================= */
  /// /* 4. SMS & USSD Operations                                                  */
  /// /* =========================================================================
  int simbox_sms_send(
    simbox_device_t dev,
    ffi.Pointer<ffi.Char> number,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _simbox_sms_send(dev, number, message);
  }

  late final _simbox_sms_sendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            simbox_device_t,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('simbox_sms_send');
  late final _simbox_sms_send = _simbox_sms_sendPtr
      .asFunction<
        int Function(
          simbox_device_t,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int simbox_ussd_send(simbox_device_t dev, ffi.Pointer<ffi.Char> code) {
    return _simbox_ussd_send(dev, code);
  }

  late final _simbox_ussd_sendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(simbox_device_t, ffi.Pointer<ffi.Char>)
        >
      >('simbox_ussd_send');
  late final _simbox_ussd_send = _simbox_ussd_sendPtr
      .asFunction<int Function(simbox_device_t, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> simbox_version() {
    return _simbox_version();
  }

  late final _simbox_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'simbox_version',
      );
  late final _simbox_version = _simbox_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class UnnamedStruct extends ffi.Struct {
  external ffi.Pointer<ffi.Char> caller;

  static ffi.Pointer<UnnamedStruct> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> caller,
  }) => $allocator<UnnamedStruct>()..ref.caller = caller;
}

final class UnnamedStruct$1 extends ffi.Struct {
  @ffi.Int()
  external int old_state;

  @ffi.Int()
  external int new_state;

  static ffi.Pointer<UnnamedStruct$1> $allocate(
    ffi.Allocator $allocator, {
    required int old_state,
    required int new_state,
  }) => $allocator<UnnamedStruct$1>()
    ..ref.old_state = old_state
    ..ref.new_state = new_state;
}

final class UnnamedStruct$2 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> sender;

  external ffi.Pointer<ffi.Char> text;

  static ffi.Pointer<UnnamedStruct$2> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> sender,
    required ffi.Pointer<ffi.Char> text,
  }) => $allocator<UnnamedStruct$2>()
    ..ref.sender = sender
    ..ref.text = text;
}

final class UnnamedStruct$3 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> response;

  static ffi.Pointer<UnnamedStruct$3> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> response,
  }) => $allocator<UnnamedStruct$3>()..ref.response = response;
}

final class UnnamedStruct$4 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> balance;

  static ffi.Pointer<UnnamedStruct$4> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> balance,
  }) => $allocator<UnnamedStruct$4>()..ref.balance = balance;
}

final class UnnamedStruct$5 extends ffi.Struct {
  @ffi.Int()
  external int error_code;

  external ffi.Pointer<ffi.Char> message;

  static ffi.Pointer<UnnamedStruct$5> $allocate(
    ffi.Allocator $allocator, {
    required int error_code,
    required ffi.Pointer<ffi.Char> message,
  }) => $allocator<UnnamedStruct$5>()
    ..ref.error_code = error_code
    ..ref.message = message;
}

final class UnnamedStruct$6 extends ffi.Struct {
  @ffi.Int()
  external int percent;

  external ffi.Pointer<ffi.Char> stage;

  static ffi.Pointer<UnnamedStruct$6> $allocate(
    ffi.Allocator $allocator, {
    required int percent,
    required ffi.Pointer<ffi.Char> stage,
  }) => $allocator<UnnamedStruct$6>()
    ..ref.percent = percent
    ..ref.stage = stage;
}

final class UnnamedUnion extends ffi.Union {
  external UnnamedStruct incoming_call;

  external UnnamedStruct$1 call_state;

  external UnnamedStruct$2 incoming_sms;

  external UnnamedStruct$3 ussd;

  external UnnamedStruct$4 balance;

  external UnnamedStruct$5 error;

  external UnnamedStruct$6 prog_progress;
}

final class simbox_config_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> config_dir;

  external ffi.Pointer<ffi.Char> state_dir;

  @ffi.Int()
  external int log_level;

  @ffi.Bool()
  external bool auto_discovery;

  @ffi.Bool()
  external bool auto_recover_diag;

  static ffi.Pointer<simbox_config_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> config_dir,
    required ffi.Pointer<ffi.Char> state_dir,
    required int log_level,
    required bool auto_discovery,
    required bool auto_recover_diag,
  }) => $allocator<simbox_config_t>()
    ..ref.config_dir = config_dir
    ..ref.state_dir = state_dir
    ..ref.log_level = log_level
    ..ref.auto_discovery = auto_discovery
    ..ref.auto_recover_diag = auto_recover_diag;
}

final class simbox_device_info_t extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> sn;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> imei;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> imsi;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> model;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> firmware;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> tty_data;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> tty_audio;

  @ffi.Int()
  external int rssi;

  @ffi.UnsignedInt()
  external int stateAsInt;

  simbox_device_state_t get state =>
      simbox_device_state_t.fromValue(stateAsInt);
  set state(simbox_device_state_t value) => stateAsInt = value.value;
}

enum simbox_device_state_t {
  SIMBOX_STATE_DISCONNECTED(0),
  SIMBOX_STATE_CONNECTING(1),
  SIMBOX_STATE_IDLE(2),
  SIMBOX_STATE_RINGING(3),
  SIMBOX_STATE_DIALING(4),
  SIMBOX_STATE_ACTIVE_CALL(5),
  SIMBOX_STATE_HOLD(6),
  SIMBOX_STATE_ERROR(7),
  SIMBOX_STATE_DIAGNOSTIC(8);

  final int value;
  const simbox_device_state_t(this.value);

  static simbox_device_state_t fromValue(int value) => switch (value) {
    0 => SIMBOX_STATE_DISCONNECTED,
    1 => SIMBOX_STATE_CONNECTING,
    2 => SIMBOX_STATE_IDLE,
    3 => SIMBOX_STATE_RINGING,
    4 => SIMBOX_STATE_DIALING,
    5 => SIMBOX_STATE_ACTIVE_CALL,
    6 => SIMBOX_STATE_HOLD,
    7 => SIMBOX_STATE_ERROR,
    8 => SIMBOX_STATE_DIAGNOSTIC,
    _ => throw ArgumentError('Unknown value for simbox_device_state_t: $value'),
  };
}

typedef simbox_device_t = ffi.Pointer<ffi.Void>;

final class simbox_discovered_device_t extends ffi.Struct {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> dev_name;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> serial_number;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> imei;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> data_port;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> audio_port;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> net_port;

  @ffi.Int()
  external int hub_port;

  @ffi.Int()
  external int vendor_id;

  @ffi.Int()
  external int product_id;
}

typedef simbox_discovery_t = ffi.Pointer<ffi.Void>;
typedef simbox_event_cb =
    ffi.Pointer<ffi.NativeFunction<simbox_event_cbFunction>>;
typedef simbox_event_cbFunction =
    ffi.Void Function(
      ffi.Pointer<simbox_event_t> event,
      ffi.Pointer<ffi.Void> userdata,
    );
typedef Dartsimbox_event_cbFunction =
    void Function(
      ffi.Pointer<simbox_event_t> event,
      ffi.Pointer<ffi.Void> userdata,
    );

final class simbox_event_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  simbox_event_type_t get type => simbox_event_type_t.fromValue(typeAsInt);
  set type(simbox_event_type_t value) => typeAsInt = value.value;

  external ffi.Pointer<ffi.Char> device_sn;

  external UnnamedUnion data;
}

enum simbox_event_type_t {
  SIMBOX_EVENT_DEVICE_CONNECTED(0),
  SIMBOX_EVENT_DEVICE_DISCONNECTED(1),
  SIMBOX_EVENT_INCOMING_CALL(2),
  SIMBOX_EVENT_CALL_STATE_CHANGED(3),
  SIMBOX_EVENT_INCOMING_SMS(4),
  SIMBOX_EVENT_USSD_RESPONSE(5),
  SIMBOX_EVENT_BALANCE_UPDATE(6),
  SIMBOX_EVENT_DEVICE_ERROR(7),
  SIMBOX_EVENT_PROG_PROGRESS(8);

  final int value;
  const simbox_event_type_t(this.value);

  static simbox_event_type_t fromValue(int value) => switch (value) {
    0 => SIMBOX_EVENT_DEVICE_CONNECTED,
    1 => SIMBOX_EVENT_DEVICE_DISCONNECTED,
    2 => SIMBOX_EVENT_INCOMING_CALL,
    3 => SIMBOX_EVENT_CALL_STATE_CHANGED,
    4 => SIMBOX_EVENT_INCOMING_SMS,
    5 => SIMBOX_EVENT_USSD_RESPONSE,
    6 => SIMBOX_EVENT_BALANCE_UPDATE,
    7 => SIMBOX_EVENT_DEVICE_ERROR,
    8 => SIMBOX_EVENT_PROG_PROGRESS,
    _ => throw ArgumentError('Unknown value for simbox_event_type_t: $value'),
  };
}

typedef simbox_handle_t = ffi.Pointer<ffi.Void>;
typedef simbox_prog_progress_cb =
    ffi.Pointer<ffi.NativeFunction<simbox_prog_progress_cbFunction>>;
typedef simbox_prog_progress_cbFunction =
    ffi.Void Function(
      ffi.Int percent,
      ffi.Pointer<ffi.Char> stage,
      ffi.Pointer<ffi.Void> userdata,
    );
typedef Dartsimbox_prog_progress_cbFunction =
    void Function(
      int percent,
      ffi.Pointer<ffi.Char> stage,
      ffi.Pointer<ffi.Void> userdata,
    );
typedef simbox_prog_t = ffi.Pointer<ffi.Void>;
typedef simbox_reader_t = ffi.Pointer<ffi.Void>;
